name: Build and push dist to deploy branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: 20
  BUILD_DIR: dist

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install deps
        run: npm ci || npm install
        working-directory: ./frontend

      # (Opcional) variables para build de prod
      - name: Write .env.production (optional)
        run: |
          if [ -n "${{ secrets.VITE_BACKEND_URL }}" ]; then echo "VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}" >> .env.production; fi
          if [ -n "${{ secrets.VITE_USE_BACKEND }}" ]; then echo "VITE_USE_BACKEND=${{ secrets.VITE_USE_BACKEND }}" >> .env.production; fi
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

      - name: Copy .htaccess into dist
        run: cp ./.htaccess ./dist/.htaccess
        working-directory: ./frontend

      # Empuja SOLO el contenido de dist al branch 'deploy'
      - name: Push dist/ to deploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: frontend/${{ env.BUILD_DIR }}
          clean: true
